openapi: 3.0.2
info:
    title: Malle-Andre-pank
    version: 1.0.0
paths:
    /users:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postUsersRequest'
                required: true
            tags:
                - users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/userObject'
                    description: User successfully registred.
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Invalid password:
                                    value:
                                        error: Invalid password
                                Parameter is required:
                                    value:
                                        error: User validation failed
                    description: Bad request.
                '409':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Username already exists:
                                    value:
                                        error: Username already exists
                    description: Username already exists.
            summary: Registers a new user
    /sessions:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/postSessionsRequest'
                required: true
            tags:
                - sessions
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/postSessionsResponse'
                    description: User logged in succesfully
                '400':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Missing username or password:
                                    value:
                                        error: Missing username or password
                    description: Missing username or password
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Invalid username or password:
                                    value:
                                        error: Invalid username or password
                    description: Invalid username or password
            summary: Logs the user in
        delete:
            tags:
                - sessions
            responses:
                '204':
                    description: User logged out successfully
                '401':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/errorResponse'
                            examples:
                                Missing Authorization header:
                                    value:
                                        error: Missing Authorization header
                                Invalid token:
                                    value:
                                        error: Invalid token
                    description: Unauthorized
            summary: Logs the user out
components:
    schemas:
        postUsersRequest:
            title: POST /users request
            description: ''
            required:
                - name
                - username
                - password
            type: object
            properties:
                name:
                    description: User's full name.
                    type: string
                username:
                    description: Chosen username.
                    type: string
                password:
                    format: password
                    description: User's password.
                    type: string
            example:
                name: Juku
                username: Uku
                password: wordpass
        userObject:
            title: userObject
            description: ''
            type: object
            properties:
                id:
                    description: User's ID.
                    type: string
                name:
                    description: User's full name.
                    type: string
                username:
                    description: Chosen username'
                    type: string
                accounts:
                    description: Array of user's bank accounts.
                    type: array
                    items:
                        $ref: '#/components/schemas/accountObject'
            example:
                id: 5f7b7ad24abdf90a746edaac
                name: Juku
                username: Uku
                accounts:
                    -
                        name: Main
                        balance: 100000
                        currency: EUR
                        number: abc84dbea2a7b4b39fac9cbb2d6469ebfab
                        id: 5f7b7ad34abdf90a746edaad
        accountObject:
            title: accountObject
            description: ''
            type: object
            properties:
                name:
                    description: Account's name.
                    type: string
                balance:
                    format: int32
                    description: The funds the account holds.
                    type: integer
                currency:
                    description: The currency of the funds.
                    type: string
                number:
                    description: Account's number.
                    type: string
            example: |-
                {
                    "name": "Main",
                    "balance": 100000,
                    "currency": "EUR",
                    "number": "abc84dbea2a7b4b39fac9cbb2d6469ebfab",
                }
        errorResponse:
            title: errorObject
            description: ''
            type: object
            properties:
                error:
                    type: string
            example:
                error: Error message.
        postSessionsRequest:
            title: POST /sessions request
            description: ''
            type: object
            properties:
                username:
                    description: A valid username
                    type: string
                password:
                    description: A valid password
                    type: string
            example:
                username: Uku
                password: wordpass
        postSessionsResponse:
            title: POST /sessions response
            description: ''
            type: object
            properties:
                token:
                    description: A session token which needs to be send back with every request to the server
                    type: string
            example:
                token: 5f8022d6f40ea213f83577fc
    securitySchemes:
        Token:
            scheme: bearer
            type: http
security:
    -
        Token: []